import glob
import os

for filepath in glob.glob('app/models/*.py'):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Fix the empty string syntax error generated by repr() around string defaults
    content = content.replace("text(''{}'::jsonb')", "text(\"'{}'::jsonb\")")
    content = content.replace("text('{}')", "text(\"{}\")")
    content = content.replace("text(''[]'::jsonb')", "text(\"'[]'::jsonb\")")
    content = content.replace("text(''free'')", "text(\"'free'\")")
    content = content.replace("text(''UTC'')", "text(\"'UTC'\")")
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
