"""add_missing_model_tables

Revision ID: 148966fd2a99
Revises: a9b8c7d6e5f4
Create Date: 2026-07-25 10:08:14.999767

Adds the 68 tables that were defined by SQLAlchemy models under app/models/
but never had a real Alembic migration -- see this migration's own commit
message / the Phase 6 test-and-fix report for the full list and root cause
(alembic/env.py's model-import list had drifted 17 files out of date,
meaning autogenerate could never see these tables at all until that was
fixed alongside this migration).

Autogenerated via `alembic revision --autogenerate`, then hand-reviewed and
filtered: the raw autogenerate output also proposed dropping and recreating
indexes/constraints on tables that already existed and were already correct
-- pure naming-convention noise (hand-written earlier migrations used an
"ix_public_..." prefix; SQLAlchemy's default naming convention doesn't).
That noise has been removed; this migration only creates the tables (and
their own indexes/FKs) that were genuinely missing. tenant_saree_inventory
was also excluded from autogenerate's proposal -- it already exists (an
orphaned table with no model, see Phase 2 finding), so a bare CREATE TABLE
for it would have failed outright.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148966fd2a99'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('erp_connectors',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('erp_type', sa.String(length=50), nullable=False),
        sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('health_status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_erp_connectors_tenant_id'), 'erp_connectors', ['tenant_id'], unique=False)
    op.create_table('finance_account_groups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=True),
        sa.Column('parent_id', sa.UUID(), nullable=True),
        sa.Column('category', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='finance_account_category'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['finance_account_groups.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_account_groups_tenant_id'), 'finance_account_groups', ['tenant_id'], unique=False)
    op.create_table('finance_ai_insights',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('insight_type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('reference_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_ai_insights_tenant_id'), 'finance_ai_insights', ['tenant_id'], unique=False)
    op.create_table('finance_ap_vendors',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('tax_number', sa.String(length=50), nullable=True),
        sa.Column('outstanding_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_ap_vendors_tenant_id'), 'finance_ap_vendors', ['tenant_id'], unique=False)
    op.create_table('finance_budgets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('fiscal_year', sa.String(length=20), nullable=False),
        sa.Column('period_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_budgets_tenant_id'), 'finance_budgets', ['tenant_id'], unique=False)
    op.create_table('finance_cash_accounts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('is_petty_cash', sa.Boolean(), nullable=False),
        sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_cash_accounts_tenant_id'), 'finance_cash_accounts', ['tenant_id'], unique=False)
    op.create_table('finance_cost_centers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('department', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_cost_centers_tenant_id'), 'finance_cost_centers', ['tenant_id'], unique=False)
    op.create_table('finance_expense_categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_expense_categories_tenant_id'), 'finance_expense_categories', ['tenant_id'], unique=False)
    op.create_table('finance_forecasts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('target_period', sa.String(length=50), nullable=False),
        sa.Column('forecast_type', sa.String(length=50), nullable=False),
        sa.Column('predicted_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_forecasts_tenant_id'), 'finance_forecasts', ['tenant_id'], unique=False)
    op.create_table('finance_profit_centers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('business_unit', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_profit_centers_tenant_id'), 'finance_profit_centers', ['tenant_id'], unique=False)
    op.create_table('migration_cleansing_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('operation', sa.String(length=50), nullable=False),
        sa.Column('source_record_id', sa.String(length=100), nullable=False),
        sa.Column('target_record_id', sa.String(length=100), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_cleansing_logs_tenant_id'), 'migration_cleansing_logs', ['tenant_id'], unique=False)
    op.create_table('migration_mapping_templates',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('mapping_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('average_confidence', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_mapping_templates_tenant_id'), 'migration_mapping_templates', ['tenant_id'], unique=False)
    op.create_table('universal_bank_accounts',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('bank_name', sa.String(length=128), nullable=False),
        sa.Column('account_number', sa.String(length=64), nullable=False),
        sa.Column('account_type', sa.String(length=32), server_default=sa.text("'CURRENT'"), nullable=False),
        sa.Column('ifsc_code', sa.String(length=32), nullable=False),
        sa.Column('branch_name', sa.String(length=128), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('current_balance', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_bank_accounts_tenant_id'), 'universal_bank_accounts', ['tenant_id'], unique=False)
    op.create_table('universal_channel_configurations',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('platform_name', sa.String(length=64), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('webhook_url', sa.String(length=256), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_channel_configurations_tenant_id'), 'universal_channel_configurations', ['tenant_id'], unique=False)
    op.create_table('universal_customer_categories',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_categories_tenant_id'), 'universal_customer_categories', ['tenant_id'], unique=False)
    op.create_table('universal_customer_groups',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_groups_tenant_id'), 'universal_customer_groups', ['tenant_id'], unique=False)
    op.create_table('universal_customer_types',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_types_tenant_id'), 'universal_customer_types', ['tenant_id'], unique=False)
    op.create_table('universal_shipping_couriers',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('courier_name', sa.String(length=128), nullable=False),
        sa.Column('tracking_url_template', sa.String(length=256), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_shipping_couriers_tenant_id'), 'universal_shipping_couriers', ['tenant_id'], unique=False)
    op.create_table('finance_ap_bills',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('vendor_id', sa.UUID(), nullable=False),
        sa.Column('bill_number', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vendor_id'], ['finance_ap_vendors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'bill_number', 'vendor_id', name='uq_tenant_vendor_bill_num')
        )
    op.create_index(op.f('ix_finance_ap_bills_tenant_id'), 'finance_ap_bills', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_ap_bills_vendor_id'), 'finance_ap_bills', ['vendor_id'], unique=False)
    op.create_table('finance_bank_reconciliations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('bank_account_id', sa.UUID(), nullable=False),
        sa.Column('statement_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('statement_balance', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('system_balance', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bank_account_id'], ['universal_bank_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_bank_reconciliations_bank_account_id'), 'finance_bank_reconciliations', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_finance_bank_reconciliations_tenant_id'), 'finance_bank_reconciliations', ['tenant_id'], unique=False)
    op.create_table('universal_bank_vouchers',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('bank_account_id', sa.UUID(), nullable=False),
        sa.Column('voucher_number', sa.String(length=64), nullable=False),
        sa.Column('voucher_type', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('reference_number', sa.String(length=128), nullable=True),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bank_account_id'], ['universal_bank_accounts.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('voucher_number')
        )
    op.create_index(op.f('ix_universal_bank_vouchers_bank_account_id'), 'universal_bank_vouchers', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_universal_bank_vouchers_tenant_id'), 'universal_bank_vouchers', ['tenant_id'], unique=False)
    op.create_table('universal_hsn_sac_codes',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('code_type', sa.String(length=16), server_default=sa.text("'HSN'"), nullable=False),
        sa.Column('tax_config_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tax_config_id'], ['universal_tax_configurations.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_hsn_sac_codes_tenant_id'), 'universal_hsn_sac_codes', ['tenant_id'], unique=False)
    op.create_table('universal_omnichannel_sync_logs',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['universal_channel_configurations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_omnichannel_sync_logs_channel_id'), 'universal_omnichannel_sync_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_universal_omnichannel_sync_logs_tenant_id'), 'universal_omnichannel_sync_logs', ['tenant_id'], unique=False)
    op.create_table('finance_ar_collections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_ar_collections_customer_id'), 'finance_ar_collections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finance_ar_collections_tenant_id'), 'finance_ar_collections', ['tenant_id'], unique=False)
    op.create_table('finance_ar_ledger',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('outstanding_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('is_bad_debt', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_tenant_customer_ar')
        )
    op.create_index(op.f('ix_finance_ar_ledger_customer_id'), 'finance_ar_ledger', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finance_ar_ledger_tenant_id'), 'finance_ar_ledger', ['tenant_id'], unique=False)
    op.create_table('finance_ar_receipts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('receipt_number', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('unallocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('payment_mode', sa.String(length=50), nullable=False),
        sa.Column('reference', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_tenant_ar_receipt_num')
        )
    op.create_index(op.f('ix_finance_ar_receipts_customer_id'), 'finance_ar_receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finance_ar_receipts_tenant_id'), 'finance_ar_receipts', ['tenant_id'], unique=False)
    op.create_table('finance_asset_categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('depreciation_method', sa.Enum('SLM', 'WDV', 'CUSTOM', name='finance_depreciation_method'), nullable=False),
        sa.Column('default_depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('asset_account_id', sa.UUID(), nullable=True),
        sa.Column('depreciation_account_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['asset_account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['depreciation_account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_asset_categories_tenant_id'), 'finance_asset_categories', ['tenant_id'], unique=False)
    op.create_table('finance_budget_lines',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('budget_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_budget_lines_budget_id'), 'finance_budget_lines', ['budget_id'], unique=False)
    op.create_index(op.f('ix_finance_budget_lines_tenant_id'), 'finance_budget_lines', ['tenant_id'], unique=False)
    op.create_table('universal_ai_billing_logs',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=True),
        sa.Column('inference_type', sa.String(length=64), nullable=False),
        sa.Column('inference_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('action_taken', sa.String(length=32), server_default=sa.text("'PENDING_REVIEW'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_ai_billing_logs_customer_id'), 'universal_ai_billing_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_ai_billing_logs_tenant_id'), 'universal_ai_billing_logs', ['tenant_id'], unique=False)
    op.create_table('universal_customer_addresses',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('address_type', sa.String(length=32), nullable=False),
        sa.Column('line1', sa.Text(), nullable=False),
        sa.Column('city', sa.String(length=128), nullable=True),
        sa.Column('state', sa.String(length=128), nullable=True),
        sa.Column('postal_code', sa.String(length=32), nullable=True),
        sa.Column('country', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_addresses_customer_id'), 'universal_customer_addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_customer_addresses_tenant_id'), 'universal_customer_addresses', ['tenant_id'], unique=False)
    op.create_table('universal_customer_contacts',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=128), nullable=True),
        sa.Column('email', sa.String(length=320), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_contacts_customer_id'), 'universal_customer_contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_customer_contacts_tenant_id'), 'universal_customer_contacts', ['tenant_id'], unique=False)
    op.create_table('universal_customer_price_lists',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_group_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_group_id'], ['universal_customer_groups.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_customer_price_lists_customer_group_id'), 'universal_customer_price_lists', ['customer_group_id'], unique=False)
    op.create_index(op.f('ix_universal_customer_price_lists_item_id'), 'universal_customer_price_lists', ['item_id'], unique=False)
    op.create_index(op.f('ix_universal_customer_price_lists_tenant_id'), 'universal_customer_price_lists', ['tenant_id'], unique=False)
    op.create_table('universal_customer_wallets',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('balance', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('customer_id')
        )
    op.create_index(op.f('ix_universal_customer_wallets_tenant_id'), 'universal_customer_wallets', ['tenant_id'], unique=False)
    op.create_table('universal_payment_receipts',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('bank_account_id', sa.UUID(), nullable=True),
        sa.Column('receipt_number', sa.String(length=64), nullable=False),
        sa.Column('payment_mode', sa.String(length=32), nullable=False),
        sa.Column('reference_number', sa.String(length=128), nullable=True),
        sa.Column('amount_received', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('unallocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'CLEARED'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bank_account_id'], ['universal_bank_accounts.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('receipt_number')
        )
    op.create_index(op.f('ix_universal_payment_receipts_customer_id'), 'universal_payment_receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_payment_receipts_tenant_id'), 'universal_payment_receipts', ['tenant_id'], unique=False)
    op.create_table('finance_ap_payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('vendor_id', sa.UUID(), nullable=False),
        sa.Column('payment_number', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('payment_mode', sa.String(length=50), nullable=False),
        sa.Column('reference', sa.String(length=100), nullable=True),
        sa.Column('unallocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('approved_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['approved_by'], ['user_profiles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vendor_id'], ['finance_ap_vendors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_tenant_ap_payment_num')
        )
    op.create_index(op.f('ix_finance_ap_payments_tenant_id'), 'finance_ap_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_ap_payments_vendor_id'), 'finance_ap_payments', ['vendor_id'], unique=False)
    op.create_table('finance_fixed_assets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=False),
        sa.Column('asset_code', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('acquisition_cost', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('salvage_value', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('useful_life_years', sa.Integer(), nullable=False),
        sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('depreciation_method', sa.Enum('SLM', 'WDV', 'CUSTOM', name='finance_depreciation_method'), nullable=False),
        sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['finance_asset_categories.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'asset_code', name='uq_tenant_asset_code')
        )
    op.create_index(op.f('ix_finance_fixed_assets_category_id'), 'finance_fixed_assets', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_fixed_assets_tenant_id'), 'finance_fixed_assets', ['tenant_id'], unique=False)
    op.create_table('migration_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('original_file_name', sa.String(length=255), nullable=True),
        sa.Column('file_path', sa.String(length=512), nullable=True),
        sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
        sa.Column('connector_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('total_records', sa.Integer(), nullable=False),
        sa.Column('valid_records', sa.Integer(), nullable=False),
        sa.Column('invalid_records', sa.Integer(), nullable=False),
        sa.Column('imported_records', sa.Integer(), nullable=False),
        sa.Column('skipped_records', sa.Integer(), nullable=False),
        sa.Column('progress_percentage', sa.Integer(), nullable=False),
        sa.Column('processing_speed_mps', sa.Float(), nullable=False),
        sa.Column('estimated_remaining_time_sec', sa.Integer(), nullable=False),
        sa.Column('data_quality_score', sa.Integer(), nullable=True),
        sa.Column('readiness_score', sa.Integer(), nullable=True),
        sa.Column('mapping_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_summary', sa.Text(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['connector_id'], ['erp_connectors.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['created_by'], ['user_profiles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_sessions_connector_id'), 'migration_sessions', ['connector_id'], unique=False)
    op.create_index(op.f('ix_migration_sessions_tenant_id'), 'migration_sessions', ['tenant_id'], unique=False)
    op.create_table('tenant_finance_ledgers',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='finance_transaction_type', schema='public'), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
        sa.Column('entry_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('metadata_insights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user_profiles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['updated_by'], ['user_profiles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_tenant_finance_ledgers_tenant_id'), 'tenant_finance_ledgers', ['tenant_id'], unique=False)
    op.create_table('universal_pos_sessions',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('session_status', sa.String(length=32), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_pos_sessions_tenant_id'), 'universal_pos_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_universal_pos_sessions_user_id'), 'universal_pos_sessions', ['user_id'], unique=False)
    op.create_table('universal_sales_orders',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('quotation_id', sa.UUID(), nullable=True),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('order_number', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column('approval_status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['quotation_id'], ['universal_sales_quotations.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_number')
        )
    op.create_index(op.f('ix_universal_sales_orders_customer_id'), 'universal_sales_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_sales_orders_tenant_id'), 'universal_sales_orders', ['tenant_id'], unique=False)
    op.create_table('universal_sales_quotation_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('quotation_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['quotation_id'], ['universal_sales_quotations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_sales_quotation_items_quotation_id'), 'universal_sales_quotation_items', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_universal_sales_quotation_items_tenant_id'), 'universal_sales_quotation_items', ['tenant_id'], unique=False)
    op.create_table('erp_import_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('connector_id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('records_fetched', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['connector_id'], ['erp_connectors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['session_id'], ['migration_sessions.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_erp_import_logs_connector_id'), 'erp_import_logs', ['connector_id'], unique=False)
    op.create_table('finance_asset_depreciation_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('asset_id', sa.UUID(), nullable=False),
        sa.Column('depreciation_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('depreciation_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('voucher_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['voucher_id'], ['finance_journal_vouchers.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_asset_depreciation_logs_asset_id'), 'finance_asset_depreciation_logs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_finance_asset_depreciation_logs_tenant_id'), 'finance_asset_depreciation_logs', ['tenant_id'], unique=False)
    op.create_table('finance_journal_entry_lines',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('voucher_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('cost_center_id', sa.UUID(), nullable=True),
        sa.Column('profit_center_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['voucher_id'], ['finance_journal_vouchers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_finance_journal_entry_lines_account_id'), 'finance_journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entry_lines_tenant_id'), 'finance_journal_entry_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entry_lines_voucher_id'), 'finance_journal_entry_lines', ['voucher_id'], unique=False)
    op.create_table('migration_data_records',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_imported', sa.Boolean(), nullable=False),
        sa.Column('target_record_id', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['migration_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_data_records_session_id'), 'migration_data_records', ['session_id'], unique=False)
    op.create_table('migration_reconciliation_reports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('missing_records', sa.Integer(), nullable=False),
        sa.Column('duplicate_records', sa.Integer(), nullable=False),
        sa.Column('mismatched_records', sa.Integer(), nullable=False),
        sa.Column('import_accuracy_percentage', sa.Float(), nullable=False),
        sa.Column('discrepancy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['migration_sessions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_reconciliation_reports_session_id'), 'migration_reconciliation_reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_migration_reconciliation_reports_tenant_id'), 'migration_reconciliation_reports', ['tenant_id'], unique=False)
    op.create_table('migration_rollback_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('records_rolled_back', sa.Integer(), nullable=False),
        sa.Column('failed_rollbacks', sa.Integer(), nullable=False),
        sa.Column('error_summary', sa.Text(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user_profiles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['migration_sessions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_rollback_logs_session_id'), 'migration_rollback_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_migration_rollback_logs_tenant_id'), 'migration_rollback_logs', ['tenant_id'], unique=False)
    op.create_table('migration_validation_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('rule_name', sa.String(length=100), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('suggestion', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['migration_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_migration_validation_logs_session_id'), 'migration_validation_logs', ['session_id'], unique=False)
    op.create_table('universal_order_channel_mappings',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('sales_order_id', sa.UUID(), nullable=True),
        sa.Column('external_order_id', sa.String(length=128), nullable=False),
        sa.Column('sync_status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['universal_channel_configurations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sales_order_id'], ['universal_sales_orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_order_channel_mappings_channel_id'), 'universal_order_channel_mappings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_universal_order_channel_mappings_external_order_id'), 'universal_order_channel_mappings', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_universal_order_channel_mappings_sales_order_id'), 'universal_order_channel_mappings', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_universal_order_channel_mappings_tenant_id'), 'universal_order_channel_mappings', ['tenant_id'], unique=False)
    op.create_table('universal_order_dispatches',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('sales_order_id', sa.UUID(), nullable=False),
        sa.Column('courier_id', sa.UUID(), nullable=True),
        sa.Column('tracking_number', sa.String(length=128), nullable=True),
        sa.Column('shipping_charges', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('dispatch_status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['courier_id'], ['universal_shipping_couriers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['sales_order_id'], ['universal_sales_orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_order_dispatches_courier_id'), 'universal_order_dispatches', ['courier_id'], unique=False)
    op.create_index(op.f('ix_universal_order_dispatches_sales_order_id'), 'universal_order_dispatches', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_universal_order_dispatches_tenant_id'), 'universal_order_dispatches', ['tenant_id'], unique=False)
    op.create_table('universal_pos_hold_bills',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('reference_name', sa.String(length=128), nullable=True),
        sa.Column('cart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['universal_pos_sessions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_pos_hold_bills_session_id'), 'universal_pos_hold_bills', ['session_id'], unique=False)
    op.create_index(op.f('ix_universal_pos_hold_bills_tenant_id'), 'universal_pos_hold_bills', ['tenant_id'], unique=False)
    op.create_table('universal_proforma_invoices',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('sales_order_id', sa.UUID(), nullable=True),
        sa.Column('pi_number', sa.String(length=64), nullable=False),
        sa.Column('revision_number', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
        sa.Column('is_tax_inclusive', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
        sa.Column('subtotal', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('total_tax', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['sales_order_id'], ['universal_sales_orders.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pi_number')
        )
    op.create_index(op.f('ix_universal_proforma_invoices_customer_id'), 'universal_proforma_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_proforma_invoices_tenant_id'), 'universal_proforma_invoices', ['tenant_id'], unique=False)
    op.create_table('universal_sales_order_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['order_id'], ['universal_sales_orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_sales_order_items_order_id'), 'universal_sales_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_universal_sales_order_items_tenant_id'), 'universal_sales_order_items', ['tenant_id'], unique=False)
    op.create_table('universal_ai_fraud_alerts',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=True),
        sa.Column('invoice_id', sa.UUID(), nullable=True),
        sa.Column('alert_type', sa.String(length=64), nullable=False),
        sa.Column('severity', sa.String(length=32), nullable=False),
        sa.Column('alert_details', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['invoice_id'], ['universal_tax_invoices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_ai_fraud_alerts_customer_id'), 'universal_ai_fraud_alerts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_ai_fraud_alerts_invoice_id'), 'universal_ai_fraud_alerts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_universal_ai_fraud_alerts_tenant_id'), 'universal_ai_fraud_alerts', ['tenant_id'], unique=False)
    op.create_table('universal_credit_notes',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('tax_invoice_id', sa.UUID(), nullable=True),
        sa.Column('note_number', sa.String(length=64), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tax_invoice_id'], ['universal_tax_invoices.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('note_number')
        )
    op.create_index(op.f('ix_universal_credit_notes_customer_id'), 'universal_credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_credit_notes_tenant_id'), 'universal_credit_notes', ['tenant_id'], unique=False)
    op.create_table('universal_debit_notes',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('tax_invoice_id', sa.UUID(), nullable=True),
        sa.Column('note_number', sa.String(length=64), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tax_invoice_id'], ['universal_tax_invoices.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('note_number')
        )
    op.create_index(op.f('ix_universal_debit_notes_customer_id'), 'universal_debit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_debit_notes_tenant_id'), 'universal_debit_notes', ['tenant_id'], unique=False)
    op.create_table('universal_delivery_challans',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('sales_order_id', sa.UUID(), nullable=True),
        sa.Column('tax_invoice_id', sa.UUID(), nullable=True),
        sa.Column('challan_number', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column('dispatch_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('vehicle_number', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['sales_order_id'], ['universal_sales_orders.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tax_invoice_id'], ['universal_tax_invoices.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('challan_number')
        )
    op.create_index(op.f('ix_universal_delivery_challans_customer_id'), 'universal_delivery_challans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_delivery_challans_tenant_id'), 'universal_delivery_challans', ['tenant_id'], unique=False)
    op.create_table('universal_payment_allocations',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('receipt_id', sa.UUID(), nullable=False),
        sa.Column('invoice_id', sa.UUID(), nullable=False),
        sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['invoice_id'], ['universal_tax_invoices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['receipt_id'], ['universal_payment_receipts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_payment_allocations_invoice_id'), 'universal_payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_universal_payment_allocations_receipt_id'), 'universal_payment_allocations', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_universal_payment_allocations_tenant_id'), 'universal_payment_allocations', ['tenant_id'], unique=False)
    op.create_table('universal_proforma_invoice_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('pi_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['pi_id'], ['universal_proforma_invoices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_proforma_invoice_items_pi_id'), 'universal_proforma_invoice_items', ['pi_id'], unique=False)
    op.create_index(op.f('ix_universal_proforma_invoice_items_tenant_id'), 'universal_proforma_invoice_items', ['tenant_id'], unique=False)
    op.create_table('universal_tax_invoice_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('invoice_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('hsn_sac_code', sa.String(length=32), nullable=True),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['invoice_id'], ['universal_tax_invoices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_tax_invoice_items_invoice_id'), 'universal_tax_invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_universal_tax_invoice_items_tenant_id'), 'universal_tax_invoice_items', ['tenant_id'], unique=False)
    op.create_table('universal_credit_note_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('note_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['note_id'], ['universal_credit_notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_credit_note_items_note_id'), 'universal_credit_note_items', ['note_id'], unique=False)
    op.create_index(op.f('ix_universal_credit_note_items_tenant_id'), 'universal_credit_note_items', ['tenant_id'], unique=False)
    op.create_table('universal_debit_note_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('note_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['note_id'], ['universal_debit_notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_debit_note_items_note_id'), 'universal_debit_note_items', ['note_id'], unique=False)
    op.create_index(op.f('ix_universal_debit_note_items_tenant_id'), 'universal_debit_note_items', ['tenant_id'], unique=False)
    op.create_table('universal_delivery_challan_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('challan_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity_dispatched', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['challan_id'], ['universal_delivery_challans.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_delivery_challan_items_challan_id'), 'universal_delivery_challan_items', ['challan_id'], unique=False)
    op.create_index(op.f('ix_universal_delivery_challan_items_tenant_id'), 'universal_delivery_challan_items', ['tenant_id'], unique=False)
    op.create_table('universal_packing_slips',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('challan_id', sa.UUID(), nullable=True),
        sa.Column('slip_number', sa.String(length=64), nullable=False),
        sa.Column('package_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
        sa.Column('total_weight', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['challan_id'], ['universal_delivery_challans.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slip_number')
        )
    op.create_index(op.f('ix_universal_packing_slips_tenant_id'), 'universal_packing_slips', ['tenant_id'], unique=False)
    op.create_table('universal_refunds',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('receipt_id', sa.UUID(), nullable=True),
        sa.Column('credit_note_id', sa.UUID(), nullable=True),
        sa.Column('bank_account_id', sa.UUID(), nullable=True),
        sa.Column('refund_number', sa.String(length=64), nullable=False),
        sa.Column('payment_mode', sa.String(length=32), nullable=False),
        sa.Column('reference_number', sa.String(length=128), nullable=True),
        sa.Column('amount_refunded', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('refund_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'CLEARED'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bank_account_id'], ['universal_bank_accounts.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['credit_note_id'], ['universal_credit_notes.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['receipt_id'], ['universal_payment_receipts.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('refund_number')
        )
    op.create_index(op.f('ix_universal_refunds_customer_id'), 'universal_refunds', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_refunds_tenant_id'), 'universal_refunds', ['tenant_id'], unique=False)
    op.create_table('universal_sales_returns',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('delivery_challan_id', sa.UUID(), nullable=True),
        sa.Column('return_number', sa.String(length=64), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['universal_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['delivery_challan_id'], ['universal_delivery_challans.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('return_number')
        )
    op.create_index(op.f('ix_universal_sales_returns_customer_id'), 'universal_sales_returns', ['customer_id'], unique=False)
    op.create_index(op.f('ix_universal_sales_returns_tenant_id'), 'universal_sales_returns', ['tenant_id'], unique=False)
    op.create_table('universal_packing_slip_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('slip_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity_packed', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['slip_id'], ['universal_packing_slips.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_packing_slip_items_slip_id'), 'universal_packing_slip_items', ['slip_id'], unique=False)
    op.create_index(op.f('ix_universal_packing_slip_items_tenant_id'), 'universal_packing_slip_items', ['tenant_id'], unique=False)
    op.create_table('universal_sales_return_items',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('return_id', sa.UUID(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.Column('quantity_returned', sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['universal_item_master.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['return_id'], ['universal_sales_returns.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_universal_sales_return_items_return_id'), 'universal_sales_return_items', ['return_id'], unique=False)
    op.create_index(op.f('ix_universal_sales_return_items_tenant_id'), 'universal_sales_return_items', ['tenant_id'], unique=False)



def downgrade() -> None:
    op.drop_table('erp_connectors')
    op.drop_table('finance_account_groups')
    op.drop_table('finance_ai_insights')
    op.drop_table('finance_ap_vendors')
    op.drop_table('finance_budgets')
    op.drop_table('finance_cash_accounts')
    op.drop_table('finance_cost_centers')
    op.drop_table('finance_expense_categories')
    op.drop_table('finance_forecasts')
    op.drop_table('finance_profit_centers')
    op.drop_table('migration_cleansing_logs')
    op.drop_table('migration_mapping_templates')
    op.drop_table('universal_bank_accounts')
    op.drop_table('universal_channel_configurations')
    op.drop_table('universal_customer_categories')
    op.drop_table('universal_customer_groups')
    op.drop_table('universal_customer_types')
    op.drop_table('universal_shipping_couriers')
    op.drop_table('finance_ap_bills')
    op.drop_table('finance_bank_reconciliations')
    op.drop_table('universal_bank_vouchers')
    op.drop_table('universal_hsn_sac_codes')
    op.drop_table('universal_omnichannel_sync_logs')
    op.drop_table('finance_ar_collections')
    op.drop_table('finance_ar_ledger')
    op.drop_table('finance_ar_receipts')
    op.drop_table('finance_asset_categories')
    op.drop_table('finance_budget_lines')
    op.drop_table('universal_ai_billing_logs')
    op.drop_table('universal_customer_addresses')
    op.drop_table('universal_customer_contacts')
    op.drop_table('universal_customer_price_lists')
    op.drop_table('universal_customer_wallets')
    op.drop_table('universal_payment_receipts')
    op.drop_table('finance_ap_payments')
    op.drop_table('finance_fixed_assets')
    op.drop_table('migration_sessions')
    op.drop_table('tenant_finance_ledgers')
    op.drop_table('universal_pos_sessions')
    op.drop_table('universal_sales_orders')
    op.drop_table('universal_sales_quotation_items')
    op.drop_table('erp_import_logs')
    op.drop_table('finance_asset_depreciation_logs')
    op.drop_table('finance_journal_entry_lines')
    op.drop_table('migration_data_records')
    op.drop_table('migration_reconciliation_reports')
    op.drop_table('migration_rollback_logs')
    op.drop_table('migration_validation_logs')
    op.drop_table('universal_order_channel_mappings')
    op.drop_table('universal_order_dispatches')
    op.drop_table('universal_pos_hold_bills')
    op.drop_table('universal_proforma_invoices')
    op.drop_table('universal_sales_order_items')
    op.drop_table('universal_ai_fraud_alerts')
    op.drop_table('universal_credit_notes')
    op.drop_table('universal_debit_notes')
    op.drop_table('universal_delivery_challans')
    op.drop_table('universal_payment_allocations')
    op.drop_table('universal_proforma_invoice_items')
    op.drop_table('universal_tax_invoice_items')
    op.drop_table('universal_credit_note_items')
    op.drop_table('universal_debit_note_items')
    op.drop_table('universal_delivery_challan_items')
    op.drop_table('universal_packing_slips')
    op.drop_table('universal_refunds')
    op.drop_table('universal_sales_returns')
    op.drop_table('universal_packing_slip_items')
    op.drop_table('universal_sales_return_items')

